default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      in_house: false
    )
  end

  desc "List Provisioning Profiles"
  lane :list_profiles do
    sh "security find-identity -v -p codesigning"
  end

  desc "Install cocoapods"
  lane :install_pods do
    cocoapods(
      clean: true,
      use_bundle_exec: false,
      repo_update: true,
      podfile: "#{ENV['IOS_BUILD_PATH']}/iOS/Podfile"
    )
  end

  desc "Build and upload to TestFlight"
  lane :build_upload_testflight do
    load_asc_api_key
    setup_ci

    puts "TEAM_ID from ENV: #{ENV['TEAM_ID']}"

    match(
      type: 'appstore',
      app_identifier: [ENV["BUNDLE_IDENTIFIER"], "#{ENV["BUNDLE_IDENTIFIER"]}.NotificationService"],
      readonly: false,
      verbose: true,
      force: true,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )

    team_id = ENV["TEAM_ID"] || lane_context[SharedValues::SIGH_PROFILE_TEAM_ID]
    puts "Using TEAM_ID: #{team_id}"

    list_profiles
    sync_code_signing(
      type: "appstore",
      app_identifier: [ENV["BUNDLE_IDENTIFIER"], "#{ENV["BUNDLE_IDENTIFIER"]}.NotificationService"],
      readonly: true
    )

    code_sign_identity = sh("security find-identity -v -p codesigning | grep 'Apple Distribution' | head -n 1 | awk -F '\"' '{print $2}'").strip

    update_code_signing_settings(
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      use_automatic_signing: false,
      team_id: team_id,
      targets: ENV["XC_TARGET_NAME"],
      code_sign_identity: code_sign_identity,
      sdk: "iphoneos*",
      profile_name: "match AppStore #{ENV["BUNDLE_IDENTIFIER"]}",
    )
    update_code_signing_settings(
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      use_automatic_signing: false,
      team_id: team_id,
      targets: "NotificationService",
      code_sign_identity: code_sign_identity,
      sdk: "iphoneos*",
      profile_name: "match AppStore #{ENV["BUNDLE_IDENTIFIER"]}.NotificationService",
    )

    version_number = ENV['MAJOR_VERSION'] || '1.0.0'
    increment_version_number(
      version_number: version_number,
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )
    increment_build_number(
      build_number: latest_testflight_build_number(
        version: version_number,
        app_identifier: ENV['BUNDLE_IDENTIFIER']
      ) + 1,
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )

    build_app(
      project: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      scheme: ENV["XC_TARGET_NAME"],
      xcargs: "-allowProvisioningUpdates IPHONEOS_DEPLOYMENT_TARGET=16.0",
      export_team_id: team_id,
      verbose: true,
      export_options: {
        method: 'app-store-connect',
        teamID: team_id,
        uploadBitcode: false,
        compileBitcode: false,
      }
    )

    upload_to_testflight(
      apple_id: ENV["APPLE_ID_DIGITS"],
      skip_waiting_for_build_processing: true
    )
  end

end
